# Generated by Django 5.2.14 on 2026-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('student', 'Student'), ('officer', 'Welfare Officer'), ('counsellor', 'Counsellor'), ('lecturer', 'Lecturer')], default='student', max_length=100),
        ),
    ]
