# Generated by Django 5.2.14 on 2026-05-29 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'ACADEMIC'), ('mental_health', 'MENTAL HEALTH'), ('physical_health', 'PHYSICAL HEALTH'), ('security', 'SECURITY'), ('financial', 'FINANCIAL'), ('other', 'OTHER')], default='security', max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default='medium', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('in_review', 'IN REVIEW'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED')], default='pending', max_length=100)),
                ('evidence_one', models.ImageField(blank=True, upload_to='report_evidence')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
