# Generated by Django 5.2.14 on 2026-05-29 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'ACADEMIC'), ('mental_health', 'MENTAL HEALTH'), ('physical_health', 'PHYSICAL HEALTH'), ('security', 'SECURITY'), ('financial', 'FINANCIAL'), ('other', 'OTHER')], default='security', max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField()),
                ('link', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource_images')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='resource_images')),
                ('file', models.FileField(blank=True, null=True, upload_to='resource_file')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=15)),
                ('specialist_to_see', models.CharField(choices=[('counsellor', 'COUNSELOR'), ('lecturer', 'LECTURER'), ('peer_mentor', 'PEER MENTOR'), ('other', 'OTHER')], default='counselor', max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'SCHEDULED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('did_not_show', 'DID NOT SHOW UP')], default='scheduled', max_length=100)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.report')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.appointment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
