# Generated by Django 5.2.14 on 2026-06-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resource_appointment_feedback_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
